on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Echo ANDROID_SDK_ROOT
        run: echo $ANDROID_SDK_ROOT
        
      - name: Replace android-hidden-api android.jar
        run: wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1f6YnnIKmke3qTQPUocCSS8d5-q7cqd-G" -O $ANDROID_SDK_ROOT/android-30/android.jar
        
      - name: Build Release with Native
        run: ./gradlew aR
        
      - name: Build Release without Native
        run: ./gradlew assembleNon_native
        
      - name: List build dir
        run: ls -l ./app/release

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: release
          path: app/release
